package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@CrossOrigin(origins = "*", allowedHeaders = "*")
@RestController
public class TeacherController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private TeacherRepo tr;
	
	
	@GetMapping(path="/allTeacher")
	  public Iterable<TeacherEntity> getAllUsers() {
	    // This returns a JSON or XML with the users
	    return tr.findAll();
	  }
	
	@PostMapping(path = "/deleteTeacher", consumes = "application/json", produces = "application/json")
	public int deletef(@RequestBody TeacherEntity Pobj)
	{
		int inx = Pobj.getId();
		tr.deleteById(inx);
		return Pobj.getId();
	}
	
	@PostMapping("/insertTeacher")
	public TeacherEntity insertf(@RequestBody TeacherEntity u)
	{
tr.save(u);		
	
	return u;
	}
	
	
	
	
}
